[build]
  command = "echo \"const config = { OPENAQ_API_KEY: '${OPENAQ_API_KEY}', WAQI_API_TOKEN: '${WAQI_API_TOKEN}' }; if (typeof window !== 'undefined') { window.APP_CONFIG = config; }\" > config.js"
  publish = "."
